[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

## 讓根路徑交給前端決定導向（避免硬轉址到 /store）

# 將 /store.html 永久導到 /store（避免空白頁）
[[redirects]]
  from = "/store.html"
  to = "/store"
  status = 301

# 會員回饋提交（服務角色）- 需置於通用 /api/* 之前
[[redirects]]
  from = "/api/orders/member/:customerId/orders/:orderId/rating"
  to = "/.netlify/functions/orders-member-rating?customerId=:customerId&orderId=:orderId"
  status = 200

[[redirects]]
  from = "/_api/orders/member/:customerId/orders/:orderId/rating"
  to = "/.netlify/functions/orders-member-rating?customerId=:customerId&orderId=:orderId"
  status = 200

# API 轉發到 Netlify Functions（/api/*）
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
[[redirects]]
  from = "/api/products-upsert"
  to = "/.netlify/functions/products-upsert"
  status = 200

[[redirects]]
  from = "/api/einvoice/create-b2c"
  to = "/.netlify/functions/einvoice-create-b2c"
  status = 200
[[redirects]]
  from = "/api/einvoice/create-b2b"
  to = "/.netlify/functions/einvoice-create-b2b"
  status = 200
[[redirects]]
  from = "/api/einvoice/cancel"
  to = "/.netlify/functions/einvoice-cancel"
  status = 200
[[redirects]]
  from = "/api/einvoice/query"
  to = "/.netlify/functions/einvoice-query"
  status = 200
[[redirects]]
  from = "/api/einvoice/print"
  to = "/.netlify/functions/einvoice-print"
  status = 200

[[redirects]]
  from = "/api/products-list"
  to = "/.netlify/functions/products-list"
  status = 200

[[redirects]]
  from = "/api/member-feedback-list"
  to = "/.netlify/functions/member-feedback-list"
  status = 200
[[redirects]]
  from = "/api/notifications-feedback-list"
  to = "/.netlify/functions/notifications-feedback-list"
  status = 200

[[redirects]]
  from = "/_api/notifications-feedback-list"
  to = "/.netlify/functions/notifications-feedback-list"
  status = 200

[[redirects]]
  from = "/api/points/apply-order"
  to = "/.netlify/functions/points-apply-order"
  status = 200
[[redirects]]
  from = "/api/points/apply-by-order"
  to = "/.netlify/functions/points-apply-by-order"
  status = 200

# Points API 映射（/_api 與 /api 皆支援，以符合前端呼叫）
[[redirects]]
  from = "/_api/points/balance"
  to = "/.netlify/functions/points-balance"
  status = 200
[[redirects]]
  from = "/api/points/balance"
  to = "/.netlify/functions/points-balance"
  status = 200

[[redirects]]
  from = "/_api/points/ledger"
  to = "/.netlify/functions/points-ledger"
  status = 200
[[redirects]]
  from = "/api/points/ledger"
  to = "/.netlify/functions/points-ledger"
  status = 200

[[redirects]]
  from = "/_api/points/pending/list"
  to = "/.netlify/functions/points-pending/list"
  status = 200
[[redirects]]
  from = "/api/points/pending/list"
  to = "/.netlify/functions/points-pending/list"
  status = 200

[[redirects]]
  from = "/_api/points/pending/create"
  to = "/.netlify/functions/points-pending/create"
  status = 200
[[redirects]]
  from = "/api/points/pending/create"
  to = "/.netlify/functions/points-pending/create"
  status = 200

[[redirects]]
  from = "/_api/points/pending/claim"
  to = "/.netlify/functions/points-pending/claim"
  status = 200
[[redirects]]
  from = "/api/points/pending/claim"
  to = "/.netlify/functions/points-pending/claim"
  status = 200

[[redirects]]
  from = "/_api/points/use-on-create"
  to = "/.netlify/functions/points-use-on-create"
  status = 200
[[redirects]]
  from = "/api/points/use-on-create"
  to = "/.netlify/functions/points-use-on-create"
  status = 200

[[redirects]]
  from = "/_api/points/apply-order"
  to = "/.netlify/functions/points-apply-order"
  status = 200

[[redirects]]
  from = "/_api/points/referral-award"
  to = "/.netlify/functions/points-referral-award"
  status = 200

[[redirects]]
  from = "/_api/points/refund-order"
  to = "/.netlify/functions/points-refund-order"
  status = 200

[[redirects]]
  from = "/api/member-code-set"
  to = "/.netlify/functions/member-code-set"
  status = 200

[[redirects]]
  from = "/api/orders/reservations"
  to = "/.netlify/functions/orders-reservations"
  status = 200

[[redirects]]
  from = "/api/reservations"
  to = "/.netlify/functions/reservations"
  status = 200

[[redirects]]
  from = "/api/member-reservations/:customerId"
  to = "/.netlify/functions/member-reservations"
  status = 200


[[redirects]]
  from = "/.well-known/*"
  to = "/.netlify/functions/:splat"
  status = 200


[[redirects]]
  from = "/shop/*"
  to = "/store/:splat"
  status = 301



[[redirects]]
  from = "/"
  to = "/store"
  status = 200
  force = true
  conditions = { Host = ["store.942clean.com.tw"] }

# SPA fallback：所有路由交給前端（/、/services/*、/store 等）
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 環境變數設定：忽略機密掃描 + 強制設定 Supabase
[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "VITE_SUPABASE_ANON_KEY,VITE_SUPABASE_URL"
  VITE_USE_SUPABASE = "1"
  VITE_SUPABASE_URL = "https://dekopbnpsvqlztabblxg.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRla29wYm5wc3ZxbHp0YWJibHhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NzkxMDgsImV4cCI6MjA3MTQ1NTEwOH0.vGeRNxRag5H4UmfuEVcju9Pt5p-i36hwfnOZaCd0x8Q"
  VITE_STRICT_SUPABASE = "1"
  VITE_QUIET_BOOT = "0"
  VITE_STORE_BASE_URL = "https://store.942clean.com.tw"
  VITE_APP_BASE_URL = "https://app.942clean.com.tw"
  # Giveme 電子發票 API（僅供 Functions 使用，避免暴露於前端）
  EINVOICE_IDNO = "api_90046766"
  EINVOICE_PASSWORD = "Api942Clean!2024"
  EINVOICE_UNCODE = "90046766"

## Cache headers：避免 index.html 舊版快取造成新 chunk 404
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
