[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

## 讓根路徑交給前端決定導向（避免硬轉址到 /store）

# 將 /store.html 永久導到 /store（避免空白頁）
[[redirects]]
  from = "/store.html"
  to = "/store"
  status = 301

# API 轉發到 Netlify Functions（/api/*）
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/api/reservations"
  to = "/.netlify/functions/reservations"
  status = 200
[[redirects]]
  from = "/api/member-reservations/*"
  to = "/.netlify/functions/member-reservations/:splat"
  status = 200


[[redirects]]
  from = "/shop/*"
  to = "/store/:splat"
  status = 301

[[redirects]]
  from = "/api/reservation-confirm/*"
  to = "/.netlify/functions/reservation-confirm/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/"
  to = "/store"
  status = 200
  force = true
  conditions = { Host = ["store.942clean.com.tw"] }

# SPA fallback：所有路由交給前端（/、/services/*、/store 等）
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 環境變數設定：忽略機密掃描 + 強制設定 Supabase
[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "VITE_SUPABASE_ANON_KEY,VITE_SUPABASE_URL"
  VITE_USE_SUPABASE = "1"
  VITE_SUPABASE_URL = "https://dekopbnpsvqlztabblxg.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRla29wYm5wc3ZxbHp0YWJibHhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NzkxMDgsImV4cCI6MjA3MTQ1NTEwOH0.vGeRNxRag5H4UmfuEVcju9Pt5p-i36hwfnOZaCd0x8Q"
  VITE_STRICT_SUPABASE = "1"
  VITE_QUIET_BOOT = "0"
  VITE_STORE_BASE_URL = "https://store.942clean.com.tw"
  VITE_APP_BASE_URL = "https://app.942clean.com.tw"

## Cache headers：避免 index.html 舊版快取造成新 chunk 404
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
